<?php
/**
 * The template for displaying posts in the Aside Post Format on index and archive pages
 *
 * Learn more: http://codex.wordpress.org/Post_Formats
 *
 * @package WordPress
 * @subpackage Twenty_Eleven
 * @since Twenty Eleven 1.0
 */
?>

	<article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
		<header class="entry-header">
			<h1 class="entry-title">
				<?php the_title(); ?>
				<?php terrific_posted_on(); ?>
				<?php edit_post_link( __( 'Edit', 'terrific' ) ); ?>
			</h1>
		</header>

		<?php if ( is_search() ) : // Only display Excerpts for Search ?>
		<div class="entry-summary">
			<?php the_excerpt(); ?>
		</div><!-- .entry-summary -->
		<?php else : ?>
		<div class="entry-content">
			<?php the_content( __( 'Continue reading <span class="meta-nav">&rarr;</span>', 'terrific' ) ); ?>
			<?php wp_link_pages( array( 'before' => '<div class="page-link"><span>' . __( 'Pages:', 'terrific' ) . '</span>', 'after' => '</div>' ) ); ?>
		</div><!-- .entry-content -->
		<?php endif; ?>

		<footer class="entry-meta">
			<?php terrific_posted_on(); ?>
			<?php if ( comments_open() ) : ?>
			<span class="sep"> | </span>
			<span class="comments-link"><?php comments_popup_link( '<span class="leave-reply">' . __( 'Leave a reply', 'terrific' ) . '</span>', __( '<b>1</b> Reply', 'terrific' ), __( '<b>%</b> Replies', 'terrific' ) ); ?></span>
			<?php endif; ?>
			<?php edit_post_link( __( 'Edit', 'terrific' ), '<span class="edit-link">', '</span>' ); ?>
		</footer>
	</article><!-- #post-<?php the_ID(); ?> -->
