<?php
/**
 * The template for displaying content in the single.php template
 *
 * @package WordPress
 * @subpackage Twenty_Eleven
 * @since Twenty Eleven 1.0
 */
?>

<article id="post-<?php the_ID(); ?>" <?php post_class('single'); ?>>
	<header class="entry-header">
		<h1 class="entry-title">
			<?php the_title(); ?>
			<?php terrific_posted_on(); ?>
			<?php edit_post_link( __( 'Edit', 'terrific' ) ); ?>
		</h1>
	</header>
	
	<?php if ( has_post_thumbnail() ) : ?>
	<div class="entry-featured-image">
	<?php the_post_thumbnail('medium') ?>
	</div>
	<?php endif; ?>
	<div class="entry-content">
		<?php the_content(); ?>
		<?php wp_link_pages( array( 'before' => '<div class="page-link"><span>' . __( 'Pages:', 'terrific' ) . '</span>', 'after' => '</div>' ) ); ?>
	</div>
</article>
